#!/usr/bin/env bash

rm -f ~/.bash_it/aliases/custom.aliases.bash 
rm -f ~/.bash_it/plugins/custom.plugins.bash
rm -f ~/.bash_it/lib/custom.bash

ln -s $(pwd)/aliases/custom.aliases.bash ~/.bash_it/aliases/custom.aliases.bash
ln -s $(pwd)/plugins/custom.plugins.bash ~/.bash_it/plugins/custom.plugins.bash
ln -s $(pwd)/lib/custom.bash ~/.bash_it/lib/custom.bash
