#!/usr/bin/env bash

rm -f ~/.bash_it/aliases/custom.aliases.bash 
rm -f ~/.bash_it/plugins/custom.plugins.bash
rm -f ~/.bash_it/lib/custom.bash
rm -f ~/.bash_it/bin

ln -s $(pwd)/bin ~/.bash_it/bin
ln -s $(pwd)/aliases/custom.aliases.bash ~/.bash_it/aliases/custom.aliases.bash
ln -s $(pwd)/plugins/custom.plugins.bash ~/.bash_it/plugins/custom.plugins.bash
ln -s $(pwd)/lib/custom.bash ~/.bash_it/lib/custom.bash

# Add git aliases
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
